<a href="https://colab.research.google.com/github/tjdudgml3/ms_aischool/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#0으로 초기화된 배열
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 빈값으로 만들어진 배열

arr = np.empty((4,4))
print(arr)

[[1.62647992e-316 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59031751e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]


In [13]:
#1로 가득찬 배열을 만든다
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#배열의 생성
# arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
# ndarray 배열의 모양,차수 ,데이터 타입 확인

arr = np.array([[2,3,4],[4,5,6]])
print(arr)

[[2 3 4]
 [4 5 6]]


In [25]:
arr.ndim

2

In [26]:
arr.dtype

dtype('int64')

In [30]:
arr_float = arr.astype(np.float64)

In [31]:
arr_float.dtype

dtype('float64')

In [42]:
arr = np.array(['1','2','5'])

In [43]:
arr = arr.astype(np.int32)
arr

array([1, 2, 5], dtype=int32)

In [50]:
list1 = [1,2,3,4]
list2 = [5,6,5,6]
list1.extend([1,2])
list1


[1, 2, 3, 4, 1, 2]

In [54]:
#배열의 연산
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[4,4],
                 [5,4],
                 [1,1]])


In [59]:
arr1+arr2

array([[5, 6],
       [8, 8]])

In [60]:
arr1 * arr2

array([[ 4,  8],
       [15, 16]])

In [61]:
np.add(arr1,arr2)

array([[5, 6],
       [8, 8]])

In [62]:
np.multiply(arr1,arr2)

array([[ 4,  8],
       [15, 16]])

In [64]:
np.dot(arr1,arr2)

array([[14, 12],
       [32, 28]])

In [65]:
#array silicing
arr = np.array([[1,2,3,],
                [4,5,6],
                [7,8,9]])



In [76]:
arr_slice = arr[:2,1:-1]
print(arr_slice)

[[2]
 [5]]


In [78]:
arr[[0,1,2],[1,1,2]]

array([2, 5, 9])

In [79]:
idx = arr>3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [85]:
arr[idx]

array([4, 5, 6, 7, 8, 9])

In [98]:
redwine = np.loadtxt(fname = 'winequality-red.csv',delimiter = ';',skiprows = 1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [89]:
print(redwine.sum())

152084.78194


In [90]:
#평균
print(redwine.mean())

7.926036165311652


In [94]:
#축(axis)
print(redwine.sum(axis = 0 ))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [96]:
print(redwine.mean(axis = 0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [99]:
redwine[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])